// swift-tools-version: 5.10
// This file is GENERATED by fresco-connect-ios/scripts/render-manifest.sh. Do not edit it by hand —
// the version and the checksum must always describe the same artifact, so they are written together
// or not at all.
//
// A deliberately low tools version: a partner on an older Xcode can still resolve this package, and
// nothing here needs a newer manifest API. The iOS floor is the FrescoConnectKit framework's, not
// this file's.
import PackageDescription

let package = Package(
  name: "fresco-connect-swift",
  // NFR1. Higher than fresco-recipe-edit-swift's 16.4, which is allowed in this direction only: a
  // consumer of this package must be on iOS 17, while RecipeEdit's own consumers need not be.
  platforms: [.iOS(.v17)],
  products: [
    // The product points at the WRAPPER, not at the binary target. A binaryTarget cannot declare
    // dependencies, so without the wrapper a consumer would link FrescoConnectKit.framework and
    // neither of the two frameworks it needs at load time.
    //
    // The product is named for the MODULE — `FrescoConnectKit` — because that is what a partner
    // imports. The public entry type inside it is `FrescoConnect`; a type may not share its
    // module's name under library evolution (spec DL-16).
    .library(name: "FrescoConnectKit", targets: ["FrescoConnectKitWrapper"])
  ],
  dependencies: [
    // Pantry is NOT named here, and that is deliberate: it arrives through
    // fresco-recipe-edit-swift's own wrapper. A second path to it from this manifest would be
    // harmless today and a resolution conflict the moment the two ranges disagree (spec §10).
    //
    // Ranges, not exact pins: a partner may depend on this package AND on fresco-recipe-edit-swift
    // directly, and SwiftPM fails a graph whose two paths to one identity disagree.
    .package(url: "https://github.com/dropkitchen/fresco-recipe-edit-swift", "0.4.0" ..< "0.5.0"),
    // This range is not a free choice: it must be one the resolved RecipeEdit also accepts.
    // fresco-recipe-edit-swift v0.4.0 declares "2.0.0" ..< "2.1.0", so this declares the same.
    // Spec §10 moves both to a 2.x range in one coordinated release (C.6.1) — never one alone.
    .package(url: "https://github.com/dropkitchen/kitchenos-client-sdk-swift", "2.0.0" ..< "2.1.0")
  ],
  targets: [
    .binaryTarget(
      name: "FrescoConnectKit",
      url: "https://github.com/dropkitchen/fresco-connect-swift/releases/download/v0.2.0/FrescoConnectKit.xcframework.zip",
      checksum: "a4cd79e39e0f59a97c216e99e1b09574d97eda3c74f3717b04cbff9888aa6068"
    ),
    .target(
      name: "FrescoConnectKitWrapper",
      dependencies: [
        "FrescoConnectKit",
        .product(name: "RecipeEdit", package: "fresco-recipe-edit-swift"),
        .product(name: "KitchenOS", package: "kitchenos-client-sdk-swift")
      ],
      path: "Sources/Wrapper"
    )
  ]
)
